"""Export Chapter 6.4 overlap-repair runs into the Chapter 5 viewer (Chapter 6 #5f).

Writes one Task-26-schema run directory per representative ch64 method directly
under ``viewers/chapter6_overlap_repair/data/ch64_<label>/`` so the existing
viewer server auto-discovers them (it scans ``runs/**/manifest.json`` and builds
geometry on demand from each frame's ``params``).

Each run dir contains:

- ``manifest.json``    -- Task-26 manifest + ``task: "ch64_overlap_repair"`` /
  ``category: "new_6_4"`` so the frontend routes it to the new category.
- ``viewer_data.json`` -- one record per start, each with exactly 50 frames
  (the ch64 trajectory resampled), augmented with overlap fields
  (``verified_overlap_norm``, ``pred_overlap_norm``, ``overlap_ok``, per-pair
  residuals, ``dominant_pair``) at both the assembly and frame level.
- ``algorithm.md``     -- short method description for the info panel.

Geometry is generated by the viewer from the per-frame clevis parameters; overlap
is shown numerically (the analytic label), so heavy-overlap meshes never need a
boolean to render.
"""

from __future__ import annotations

import argparse
import json
import math
from datetime import datetime, timezone
from pathlib import Path

from .label_cache import STRICT_THRESHOLD_NORM
from .regression_metrics import PAIR_COLUMNS
from .sampler import DummyParams
from ._public_helpers import _strict_label

_PARAM_FIELDS = set(DummyParams.__dataclass_fields__)

from .release_paths import REPAIR_CH64_DIR, VIEWER_RUNS_DIR

PARAM_NAMES = [
    "wall_thickness", "outer_span", "leg_length", "depth",
    "main_hole_offset_from_open_end", "main_hole_radius",
    "main_pin_length", "main_pin_radius",
    "cross_hole_radius", "cross_hole_distance_from_free_end",
    "splint_radius", "splint_length", "overhang_span_y",
]

# Matches the viewer's PARAM_RANGES (used only for the displayed normalized distance).
PARAM_RANGES = {
    "wall_thickness": (2.0, 12.0), "outer_span": (30.0, 100.0), "leg_length": (20.0, 80.0),
    "depth": (12.0, 60.0), "main_hole_offset_from_open_end": (2.0, 62.0), "main_hole_radius": (2.0, 10.0),
    "main_pin_length": (39.0, 182.0), "main_pin_radius": (1.5, 10.0), "cross_hole_radius": (1.0, 5.5),
    "cross_hole_distance_from_free_end": (1.5, 30.0), "splint_radius": (0.8, 4.0),
    "splint_length": (7.0, 42.0), "overhang_span_y": (24.0, 200.0),
}

N_FRAMES = 50

METHOD_LABELS = {
    "mlp__v3__tauvol0": ("mlp_only_v3", "MLP-only (v3 single-head)"),
    "hybrid_lite__v3__tauvol0": ("hybrid_lite_v3", "Hybrid-lite (MLP + bounded direct polish)"),
    "hybrid_lite_reduced_calls__v3__tauvol0": (
        "hybrid_lite_reduced_calls_v3",
        "Hybrid-lite reduced-calls (v3)",
    ),
    "finish_line__v3__tauvol0": ("finish_line_v3", "Finish-line (MLP path extrapolation)"),
    "full_hybrid__v3__tauvol0": ("full_hybrid_v3", "Full hybrid (MLP + deep direct cleanup)"),
    "random_direct__none": ("random_direct", "Random directions + direct verify (control)"),
    "axis_direct__none": ("axis_direct", "Coordinate-axis + direct verify (control)"),
    "hybrid_lite__multitask__taubin0.1": (
        "hybrid_lite_multitask_taubin01",
        "Hybrid-lite (multitask, tau_bin=0.1)",
    ),
    "mlp__multitask__taubin0.1": ("mlp_multitask_taubin01", "MLP-only (multitask, binary-head stop)"),
}

DEFAULT_METHODS = [
    "mlp__v3__tauvol0",
    "hybrid_lite__v3__tauvol0",
    "finish_line__v3__tauvol0",
    "random_direct__none",
    "axis_direct__none",
]


def _load_method_results(runs_root: Path, method_label: str) -> list[dict]:
    rows: list[dict] = []
    for f in sorted(runs_root.glob(f"{method_label}/shard_*/results.json")):
        rows.extend(json.loads(f.read_text(encoding="utf-8")))
    if not rows:
        single = runs_root / method_label / "results.json"
        if single.exists():
            rows = json.loads(single.read_text(encoding="utf-8"))
    rows.sort(key=lambda r: (r.get("strict_category", ""), float(r.get("start_overlap_norm", 0.0))))
    return rows


def _norm_distance(params: dict, start_params: dict) -> float:
    total = 0.0
    for name in PARAM_NAMES:
        lo, hi = PARAM_RANGES[name]
        span = (hi - lo) or 1.0
        total += ((float(params.get(name, 0.0)) - float(start_params.get(name, 0.0))) / span) ** 2
    return math.sqrt(total)


def _resample_indices(n_traj: int) -> list[int]:
    if n_traj <= 1:
        return [0] * N_FRAMES
    return [round(i * (n_traj - 1) / (N_FRAMES - 1)) for i in range(N_FRAMES)]


def _pair_residuals(params: dict) -> tuple[dict[str, float], str]:
    """Recompute the analytic per-pair overlap residuals for a frame's geometry."""
    try:
        dp = DummyParams(**{k: float(v) for k, v in params.items() if k in _PARAM_FIELDS})
        label = _strict_label(dp)
    except Exception:  # noqa: BLE001 - viewer cosmetics must never break the export
        return {p: float("nan") for p in PAIR_COLUMNS}, ""
    pairs = {p: float(label.get(f"pair_norm_{p}", 0.0)) for p in PAIR_COLUMNS}
    dominant = str(label.get("dominant_pair", ""))
    if dominant == "clean":
        dominant = ""
    return pairs, dominant


def _frame_record(
    traj_frame: dict, frame_idx: int, start_params: dict,
    *, terminated: bool, stop_reason: str, pairs: dict[str, float], dominant: str,
) -> dict:
    params = traj_frame["params"]
    verified = float(traj_frame["verified_overlap_norm"])
    pred = traj_frame.get("pred_overlap_norm")
    ok = bool(traj_frame.get("overlap_ok", verified <= STRICT_THRESHOLD_NORM))
    return {
        "frame_idx": frame_idx,
        "params": params,
        # Reuse the probability channel as a "fraction-cleared" cue for coloring.
        "probability": 1.0 if ok else None,
        "gradient_direction": None,
        "step_magnitude": None,
        "normalized_distance": _norm_distance(params, start_params),
        "valid": True,
        "oracle_label": 1 if ok else 0,
        "oracle_reason": "clean" if ok else (dominant or "overlap"),
        "terminated": terminated,
        "termination_frame": None,
        "stop_reason": stop_reason if terminated else None,
        # Overlap-aware fields:
        "verified_overlap_norm": verified,
        "pred_overlap_norm": (None if pred is None else float(pred)),
        "overlap_ok": ok,
        "phase": traj_frame.get("phase", ""),
        "pair_residuals": pairs,
        "dominant_pair": dominant,
    }


def _assembly_record(result: dict) -> dict:
    traj = result.get("trajectory", [])
    if not traj:
        return {}
    start_params = traj[0]["params"]
    n = len(traj)
    indices = _resample_indices(n)
    first_final = next((i for i, idx in enumerate(indices) if idx == n - 1), N_FRAMES - 1)
    stop_reason = str(result.get("mlp_stop_reason", result.get("stop_reason", "")))
    # Recompute per-pair residuals once per unique trajectory frame, then reuse.
    pair_cache = {idx: _pair_residuals(traj[idx]["params"]) for idx in sorted(set(indices))}
    frames = [
        _frame_record(
            traj[idx], i, start_params, terminated=(i >= first_final), stop_reason=stop_reason,
            pairs=pair_cache[idx][0], dominant=pair_cache[idx][1],
        )
        for i, idx in enumerate(indices)
    ]
    start_norm = float(result["start_overlap_norm"])
    final_norm = float(result["final_overlap_norm"])
    success = bool(result["success"])
    pct = float(result.get("pct_overlap_reduction", 0.0))
    pairs = pair_cache[indices[-1]][0]
    explanation = (
        f"method={result.get('method','')}  category={result.get('strict_category','')}\n"
        f"start overlap={start_norm:.3e}  final overlap={final_norm:.3e}\n"
        f"overlap reduction={pct:.1f}%  strict success={'yes' if success else 'no'}\n"
        f"stop={stop_reason}  active coords={result.get('active_coordinates','—')}  "
        f"verifier calls={result.get('verifier_calls','—')}\n"
        f"final pair residuals: " + ", ".join(f"{p}={pairs[p]:.2e}" for p in PAIR_COLUMNS)
    )
    return {
        "start_id": result.get("sample_id", ""),
        "subgroup": result.get("strict_category", ""),
        "status": "overlap_cleared" if success else "overlap_remaining",
        "oracle_label": 1 if success else 0,
        "oracle_reason": ("clean" if success else (pair_cache[indices[-1]][1] or "overlap")),
        "normalized_distance": float(result.get("distance", frames[-1]["normalized_distance"])),
        "start_probability": 0.0,
        "final_probability": 1.0 if success else 0.0,
        "threshold": STRICT_THRESHOLD_NORM,
        "stop_reason": stop_reason,
        "blocked_explanation": explanation,
        "frames": frames,
        # Overlap-aware run/assembly markers consumed by the frontend.
        "kind": "overlap_repair",
        "overlap_mode": True,
        "method": result.get("method", ""),
        "success": success,
        "start_overlap_norm": start_norm,
        "final_overlap_norm": final_norm,
        "pct_overlap_reduction": pct,
        "start_magnitude_bin": result.get("start_magnitude_bin", ""),
    }


def _algorithm_md(method_label: str, title: str, results: list[dict]) -> str:
    succ = sum(bool(r["success"]) for r in results)
    n = len(results)
    mean_red = sum(float(r.get("pct_overlap_reduction", 0.0)) for r in results) / max(n, 1)
    mean_verif = sum(float(r.get("verifier_calls", 0.0)) for r in results) / max(n, 1)
    return (
        f"# {title}\n\n"
        f"Chapter 6.4 overlap-only strict repair (`{method_label}`) on the frozen "
        f"50-start benchmark `strict_overlap_repair_ch64_v1`.\n\n"
        f"- Strict success (analytic overlap <= 1e-6): **{succ}/{n}**\n"
        f"- Mean overlap-volume reduction (incl. failures): **{mean_red:.1f}%**\n"
        f"- Mean verifier (analytic overlap) calls: **{mean_verif:.0f}**\n\n"
        "Each frame shows the clevis at one accepted repair step; the overlap panel "
        "reports the analytic overlap volume, the strict `overlap_ok` flag, and the "
        "per-pair residuals. Geometry is generated on demand from the frame parameters.\n"
    )


def _write_run(method_label: str, results: list[dict], out_root: Path) -> Path:
    short, title = METHOD_LABELS.get(method_label, (method_label, method_label))
    run_id = f"ch64_{short}"
    run_dir = out_root / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    assemblies = [a for a in (_assembly_record(r) for r in results) if a]
    (run_dir / "viewer_data.json").write_text(json.dumps(assemblies, indent=2), encoding="utf-8")

    succ = sum(a["success"] for a in assemblies)
    n = len(assemblies)
    mean_red = sum(a["pct_overlap_reduction"] for a in assemblies) / max(n, 1)
    mean_dist = sum(a["normalized_distance"] for a in assemblies) / max(n, 1)
    manifest = {
        "schema_version": "v1",
        "run_id": run_id,
        "optimizer_id": method_label,
        "model_id": "overlap_regressor_v3" if "v3" in method_label else ("overlap_regressor_multitask_v1" if "multitask" in method_label else "none"),
        "benchmark_set": "strict_overlap_repair_ch64_v1",
        "tau": STRICT_THRESHOLD_NORM,
        "n_starts": n,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "task": "ch64_overlap_repair",
        "category": "new_6_4",
        "title": title,
        "results_summary": {
            "oracle_confirmed": succ,
            "false_success": 0,
            "mean_distance": mean_dist,
            "strict_success": succ,
            "mean_pct_overlap_reduction": mean_red,
        },
    }
    (run_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (run_dir / "algorithm.md").write_text(_algorithm_md(method_label, title, results), encoding="utf-8")
    print(f"  {run_id}: {n} starts, strict success {succ}/{n}, mean reduction {mean_red:.1f}%")
    return run_dir


def run(args: argparse.Namespace) -> Path:
    out_root = args.out_root
    out_root.mkdir(parents=True, exist_ok=True)
    methods = [m for m in args.methods.split(",") if m] or DEFAULT_METHODS
    for method_label in methods:
        results = _load_method_results(args.runs_root, method_label)
        if not results:
            print(f"  (skip {method_label}: no results)")
            continue
        _write_run(method_label, results, out_root)
    print(out_root)
    return out_root


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-root", type=Path, default=REPAIR_CH64_DIR)
    parser.add_argument("--out-root", type=Path, default=VIEWER_RUNS_DIR)
    parser.add_argument("--methods", default=",".join(DEFAULT_METHODS))
    args = parser.parse_args()
    run(args)


if __name__ == "__main__":
    main()
